name: Rubrum
version: '${project.version}'
description: Assistance in modifying NBTs in multiple versions.
authors: [ A4Z0 ]

main: com.a4z0.rubrum.Rubrum
load: POSTWORLD
database: false
api-version: 1.13